# Base Config
PROJECT_NAME: ScienceQA_Text_Faiss_MiniLM-L6-v2_woCoT_wnewprompt_wimgpath_bug_fix
## Dataset Config
DATASET_NAME: ScienceQA  # dataset name, e.g., ok, aok
DATASET_PATH:
    DATA_ROOT: /home/xiaochen/RCTS-RAG/Dataset/ScienceQA/data/scienceqa

INDEX_TYPE: faiss

## EMBEDDING MODEL
INDEX_MODEL:
    EMBEDDING_MODEL:
        MODEL_NAME: all-MiniLM-L6-v2
        MODEL_PATH: sentence-transformers/all-MiniLM-L6-v2

# Other Config
DATASET_PATH_CONFIG: configs/dataset_path.yaml
TASK_CONFIG: configs/task_config.yaml

# Logger Config
WITH_TIME: False
LOG_DIR_ORI: ./logs/